esphome:
  name: esphome-displayx
  friendly_name: esphome-displayx

  on_boot:
    then:
      - output.turn_off: LED_green

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "GFS61WTp2DRK+e2bznsslawMV6jbzzU5i4IFnY1HamE="

ota:
  password: "aad6ea7d7d0be40f41b392e6c220d978"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Displayx"
    password: "NenxJrXykxrh"

captive_portal:

output:
  - platform: gpio
    pin: D0
    id: "LED_green"

time:
  - platform: homeassistant
    id: esptime

sensor:
  - platform: homeassistant
    name: "christian_temp"
    id: christian_temp
    entity_id: sensor.tempsensor_iii_temperature

  - platform: homeassistant
    name: "aussen_temp"
    id: aussen_temp
    entity_id: sensor.abus_multisensor_air_temperature

spi:
  clk_pin: D6 #SCL
  mosi_pin: D5 #SDA
display:
  - platform: st7735
    model: "INITR_BLACKTAB"
    reset_pin: D4 #RES
    cs_pin: D1 #CS
    dc_pin: D2 #DC
    rotation: 90
    device_width: 128
    device_height: 160
    col_start: 0
    row_start: 0
    eight_bit_color: True
    update_interval: 5s
    lambda: |-
      it.strftime(0, 0, id(font3), TextAlign::TOP_LEFT, "%d", id(esptime).now());
      it.strftime(0, 25, id(font2), TextAlign::TOP_LEFT, "%b", id(esptime).now());
      it.strftime(160, 0, id(font4), TextAlign::TOP_RIGHT, "%H:%M", id(esptime).now());
      it.rectangle(0, 45, 160, 40, Color(255,171,0));
      it. printf(5, 44, id(font1), TextAlign::TOP_LEFT , " Christian ");
      it.printf(5, 82, id(font4), Color(255,171,0), TextAlign::BASELINE_LEFT , "%.1f°C", id(christian_temp).state);
      it.rectangle(0, 88, 160, 40, Color(64,70,215));
      it. printf(5, 87, id(font1), TextAlign::TOP_LEFT , " Aussen ");
      it.printf(5, 125, id(font4), Color(64,70,215), TextAlign::BASELINE_LEFT , "%.1f°C", id(aussen_temp).state);

font:
  - file: "LiberationSans-Regular.ttf"
    id: font1
    size: 10
  - file: "LiberationSans-Regular.ttf"
    id: font2
    size: 18
  - file: "LiberationSans-Regular.ttf"
    id: font3
    size: 24
  - file: "LiberationSans-Regular.ttf"
    id: font4
    size: 38
